# Site settings
title: Sam Isenhower
description: College Station based videographer specializing in digital marketing for small businesses
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: GET THROUGH
user_description: I'm a videographer based in College Station, TX, and I love helping businesses get customers. I can help you become ever-present on social media, boost your SEO, deliver effective targeted ads, craft your video bids and pitches, or whatever it is that your business needs.
user_title: VIDEOGRAPHER
email: video@samisenhower.com
instagram_username: sam.isenhower
facebook_username: sammisenhower
linkedin_username: samisenhower
vimeo_username: samisenhower
youtube_username: samisenhower

exclude: ['package.json', 'src', 'node_modules', 'vendor']


